name: Merge dev into main after PR approval and successful tests

on: pull_request
   
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: run install, build and test
        run: |
          npm install
          npm run build
          npm test

      
 
  # merge:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Set up Git
  #       run: |
  #         git config user.name "github-actions"
  #         git config user.email "github-actions@github.com"

  #     - name: Fetch all branches
  #       run: git fetch origin

  #     - name: Merge dev into main
  #       run: |
  #         git checkout main
  #         git pull origin main
  #         git merge origin/dev --no-ff -m "Merge dev into main after successful tests"
  #         git push origin main

  #     - name: Done!
  #       run: echo "✅ Merge realizado com sucesso!"
