name: Test and auto-merge PRs

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install, build and test
        run: |
          npm install --legacy-peer-deps
          npm run build
          npm test

  enable-automerge:
    needs: test
    runs-on: ubuntu-latest
    if: github.actor == 'KlaytonDias'
    permissions:
      pull-requests: write
    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
          